name: jc_service_wrapper
description: "A service wrapper for firebase and huawei for my project"
version: 0.0.1
homepage: https://github.com/chzhhong97/flutter_packages

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_timezone:
  flutter_local_notifications:
  flutter_hms_gms_availability:
  permission_handler:
  package_info_plus:
  path_provider:
  timezone:
  intl:
  jc_utils:
    git:
      url: https://github.com/chzhhong97/flutter_packages.git
      path: packages/jc_utils

  ## HUAWEI
  huawei_push:
  huawei_location:
    git:
      url: https://github.com/chzhhong97/hms-flutter-plugin.git
      ref: master
      path: flutter-hms-location
  agconnect_crash:
  agconnect_core:
  ## GOOGLE
  firebase_messaging:
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:
  geolocator:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
